// Mock data with realistic Nepali content for Pasal Khata

export const mockCustomers = [
  {
    id: 'c1',
    name: 'Suresh Tamang',
    nameNepali: 'सुरेश तामाङ',
    phone: '9841234567',
    address: 'Baneshwor, Kathmandu',
    memberSince: '2024-01-15',
    totalBought: 12500,
    totalPaid: 9000,
    baki: 3500,
    lastPurchase: '2026-08-10',
  },
  {
    id: 'c2',
    name: 'Radha Sharma',
    nameNepali: 'राधा शर्मा',
    phone: '9851098765',
    address: 'Koteshwor, Kathmandu',
    memberSince: '2024-02-20',
    totalBought: 8750,
    totalPaid: 5250,
    baki: 3500,
    lastPurchase: '2026-08-12',
  },
  {
    id: 'c3',
    name: 'Manoj Karki',
    nameNepali: 'मनोज कार्की',
    phone: '9863456789',
    address: 'Lalitpur, Patan',
    memberSince: '2024-03-10',
    totalBought: 21000,
    totalPaid: 15500,
    baki: 5500,
    lastPurchase: '2026-08-11',
  },
  {
    id: 'c4',
    name: 'Sita Thapa',
    nameNepali: 'सिता थापा',
    phone: '9876543210',
    address: 'Kirtipur, Kathmandu',
    memberSince: '2024-04-05',
    totalBought: 15200,
    totalPaid: 12700,
    baki: 2500,
    lastPurchase: '2026-08-09',
  },
  {
    id: 'c5',
    name: 'Ram Bahadur Rai',
    nameNepali: 'राम बहादुर राई',
    phone: '9812345678',
    address: 'Bhaktapur',
    memberSince: '2024-05-12',
    totalBought: 9800,
    totalPaid: 6450,
    baki: 3350,
    lastPurchase: '2026-08-13',
  },
];

export const mockProducts = [
  {
    id: 'p1',
    name: 'Basmati Rice',
    nameNepali: 'बासमती चामल',
    category: 'Grain',
    price: 180,
    unit: 'kg',
    stock: 250,
    lowStockThreshold: 20,
  },
  {
    id: 'p2',
    name: 'Musuri Dal',
    nameNepali: 'मुसुरीको दाल',
    category: 'Pulse',
    price: 160,
    unit: 'kg',
    stock: 8,
    lowStockThreshold: 10,
  },
  {
    id: 'p3',
    name: 'Sunflower Oil',
    nameNepali: 'सूर्यमुखी तेल',
    category: 'Oil',
    price: 250,
    unit: 'ltr',
    stock: 45,
    lowStockThreshold: 10,
  },
  {
    id: 'p4',
    name: 'Ilam Tea',
    nameNepali: 'इलाम चिया',
    category: 'Beverage',
    price: 320,
    unit: 'packet',
    stock: 30,
    lowStockThreshold: 5,
  },
  {
    id: 'p5',
    name: 'Chini (Sugar)',
    nameNepali: 'चिनी',
    category: 'Sweetener',
    price: 95,
    unit: 'kg',
    stock: 5,
    lowStockThreshold: 10,
  },
  {
    id: 'p6',
    name: 'Noon (Salt)',
    nameNepali: 'नुन',
    category: 'Spice',
    price: 30,
    unit: 'packet',
    stock: 60,
    lowStockThreshold: 10,
  },
  {
    id: 'p7',
    name: 'Wai Wai Noodles',
    nameNepali: 'वाईवाई नुडल्स',
    category: 'Instant Food',
    price: 25,
    unit: 'packet',
    stock: 120,
    lowStockThreshold: 20,
  },
  {
    id: 'p8',
    name: 'Britannia Biscuit',
    nameNepali: 'ब्रिटानिया बिस्कुट',
    category: 'Snack',
    price: 40,
    unit: 'packet',
    stock: 80,
    lowStockThreshold: 15,
  },
];

export const mockSales = [
  {
    id: 's1',
    customerId: 'c1',
    customerName: 'Suresh Tamang',
    items: [
      { productId: 'p1', name: 'Basmati Rice', qty: 5, price: 180, total: 900 },
      { productId: 'p3', name: 'Sunflower Oil', qty: 2, price: 250, total: 500 },
    ],
    total: 1400,
    paid: 1000,
    baki: 400,
    date: '2026-08-10',
    status: 'partial',
  },
  {
    id: 's2',
    customerId: 'c2',
    customerName: 'Radha Sharma',
    items: [
      { productId: 'p2', name: 'Musuri Dal', qty: 3, price: 160, total: 480 },
      { productId: 'p5', name: 'Chini (Sugar)', qty: 2, price: 95, total: 190 },
      { productId: 'p6', name: 'Noon (Salt)', qty: 1, price: 30, total: 30 },
    ],
    total: 700,
    paid: 700,
    baki: 0,
    date: '2026-08-12',
    status: 'paid',
  },
  {
    id: 's3',
    customerId: 'c3',
    customerName: 'Manoj Karki',
    items: [
      { productId: 'p1', name: 'Basmati Rice', qty: 10, price: 180, total: 1800 },
      { productId: 'p4', name: 'Ilam Tea', qty: 2, price: 320, total: 640 },
      { productId: 'p7', name: 'Wai Wai Noodles', qty: 12, price: 25, total: 300 },
    ],
    total: 2740,
    paid: 1500,
    baki: 1240,
    date: '2026-08-11',
    status: 'partial',
  },
  {
    id: 's4',
    customerId: 'c4',
    customerName: 'Sita Thapa',
    items: [
      { productId: 'p3', name: 'Sunflower Oil', qty: 3, price: 250, total: 750 },
      { productId: 'p8', name: 'Britannia Biscuit', qty: 5, price: 40, total: 200 },
    ],
    total: 950,
    paid: 950,
    baki: 0,
    date: '2026-08-09',
    status: 'paid',
  },
  {
    id: 's5',
    customerId: 'c5',
    customerName: 'Ram Bahadur Rai',
    items: [
      { productId: 'p1', name: 'Basmati Rice', qty: 8, price: 180, total: 1440 },
      { productId: 'p2', name: 'Musuri Dal', qty: 4, price: 160, total: 640 },
      { productId: 'p6', name: 'Noon (Salt)', qty: 2, price: 30, total: 60 },
    ],
    total: 2140,
    paid: 1000,
    baki: 1140,
    date: '2026-08-13',
    status: 'partial',
  },
  {
    id: 's6',
    customerId: 'c1',
    customerName: 'Suresh Tamang',
    items: [
      { productId: 'p7', name: 'Wai Wai Noodles', qty: 10, price: 25, total: 250 },
      { productId: 'p8', name: 'Britannia Biscuit', qty: 6, price: 40, total: 240 },
    ],
    total: 490,
    paid: 0,
    baki: 490,
    date: '2026-08-14',
    status: 'baki',
  },
  {
    id: 's7',
    customerId: 'c2',
    customerName: 'Radha Sharma',
    items: [
      { productId: 'p4', name: 'Ilam Tea', qty: 1, price: 320, total: 320 },
      { productId: 'p5', name: 'Chini (Sugar)', qty: 3, price: 95, total: 285 },
    ],
    total: 605,
    paid: 500,
    baki: 105,
    date: '2026-08-14',
    status: 'partial',
  },
  {
    id: 's8',
    customerId: 'c3',
    customerName: 'Manoj Karki',
    items: [
      { productId: 'p3', name: 'Sunflower Oil', qty: 5, price: 250, total: 1250 },
    ],
    total: 1250,
    paid: 1250,
    baki: 0,
    date: '2026-08-08',
    status: 'paid',
  },
  {
    id: 's9',
    customerId: 'c4',
    customerName: 'Sita Thapa',
    items: [
      { productId: 'p1', name: 'Basmati Rice', qty: 6, price: 180, total: 1080 },
      { productId: 'p2', name: 'Musuri Dal', qty: 2, price: 160, total: 320 },
      { productId: 'p6', name: 'Noon (Salt)', qty: 3, price: 30, total: 90 },
    ],
    total: 1490,
    paid: 1000,
    baki: 490,
    date: '2026-08-07',
    status: 'partial',
  },
  {
    id: 's10',
    customerId: 'c5',
    customerName: 'Ram Bahadur Rai',
    items: [
      { productId: 'p7', name: 'Wai Wai Noodles', qty: 20, price: 25, total: 500 },
      { productId: 'p8', name: 'Britannia Biscuit', qty: 10, price: 40, total: 400 },
    ],
    total: 900,
    paid: 900,
    baki: 0,
    date: '2026-08-06',
    status: 'paid',
  },
];

export const mockPayments = [
  {
    id: 'pay1',
    customerId: 'c1',
    customerName: 'Suresh Tamang',
    amount: 1000,
    date: '2026-08-10',
    note: 'Cash payment',
    method: 'cash',
  },
  {
    id: 'pay2',
    customerId: 'c3',
    customerName: 'Manoj Karki',
    amount: 2500,
    date: '2026-08-11',
    note: 'Esewa transfer',
    method: 'esewa',
  },
  {
    id: 'pay3',
    customerId: 'c2',
    customerName: 'Radha Sharma',
    amount: 700,
    date: '2026-08-12',
    note: 'Full payment',
    method: 'cash',
  },
  {
    id: 'pay4',
    customerId: 'c4',
    customerName: 'Sita Thapa',
    amount: 950,
    date: '2026-08-09',
    note: 'Mobile banking',
    method: 'banking',
  },
  {
    id: 'pay5',
    customerId: 'c5',
    customerName: 'Ram Bahadur Rai',
    amount: 1000,
    date: '2026-08-13',
    note: 'Partial payment',
    method: 'cash',
  },
];

// Combined timeline for a customer (used in CustomerDetail / MyKhata)
export function getCustomerTimeline(customerId) {
  const sales = mockSales
    .filter(s => s.customerId === customerId)
    .map(s => ({ ...s, type: 'sale' }));

  const payments = mockPayments
    .filter(p => p.customerId === customerId)
    .map(p => ({ ...p, type: 'payment' }));

  return [...sales, ...payments].sort((a, b) =>
    new Date(b.date || b.createdAt) - new Date(a.date || a.createdAt)
  );
}

export const dashboardStats = {
  todaySales: 4250,
  cashReceived: 3100,
  totalBaki: 28450,
  totalCustomers: 5,
};
